### ISSUE TITLE
How do you run this on linux

### ISSUE THREAD

**Issue by shreyasajj** [mwhudson/livefs-editor#13]
Hi, I'm trying to use your autosetup python programs, but im not sure how to set it up.

**Comment by shreyasajj** [comment]
I have tried `python3 -m livefs_edit fwiw` but it keeps telling me
```
n__.py", line 35, in main
    destpath = argv[1]
IndexError: list index out of range
```

**Comment by mwhudson** [comment]
You need to pass a source and destination path as a minimum. The argument parsing is a bit custom and strange, if I used a more normal package I guess I'd get better error reporting.
