### ISSUE TITLE
setup_rootfs and runtime kernel command line args

### ISSUE THREAD

**Issue by dbungert** [mwhudson/livefs-editor#2]
If one uses livefs-editor to inject a snap, or presumably anything that uses setup_rootfs, there is a layerfs-path arg added to the kernel command line.
If one then takes the resulting iso, and attempts to boot it with kvm and supply arguments with -append, that nice custom layer is not present.
A workaround would be to use add_cmdline_arg to build in the arguments that would be supplied with kvm -append, which is arguably more convenient in the first place, but it's not clear that this would be needed without a bit of head scratching on why the setup_rootfs operation didn't seem to take.

**Comment by mwhudson** [comment]
I guess livefs-editor should replace the layer-path wherever it was found: if it came from the grub config (like in the desktop canary ISOs) we should change it there, if it came from the initrd (like the live server ISOs), we should change it there.

(I'll probably try to change the canary ISOs to set it in the initrd at some point)

**Comment by mwhudson** [comment]
I fixed this in 3f6643c316321b7e68b72f767c09eda99914375a but forgot there was a bug report about it.
