### ISSUE TITLE
add-debs-to-pool does not overwrite old packages

### ISSUE THREAD

**Issue by xypron** [mwhudson/livefs-editor#46]
Hello @mwhudson 

In my work directory I have:

```
libefivar1_37-6ubuntu3_riscv64.deb
libefiboot1_37-6ubuntu3_riscv64.deb
```

My update.yaml contains
```
- name: add-debs-to-pool
  debs:
  - libefivar1_37-6ubuntu3_riscv64.deb
  - libefiboot1_37-6ubuntu3_riscv64.deb
```

After the update I see:

```
/pool/main/e/efivar/libefiboot1_37-6ubuntu2_riscv64.deb
/pool/main/e/efivar/libefivar1_37-6ubuntu2_riscv64.deb
/pool/main/libefiboot1_37-6ubuntu3_riscv64.deb
/pool/main/libefivar1_37-6ubuntu3_riscv64.deb
```

There should never be two versions of the same package in the pool.

Best regards

Heinrich

**Comment by xypron** [comment]
/mnt/dists/mantic/main/binary-riscv64/Packages.gz has entries for both versions:

```
Package: libefivar1
Architecture: riscv64
Version: 37-6ubuntu2

Package: libefivar1
Architecture: riscv64
Version: 37-6ubuntu3
```

**Comment by xypron** [comment]
With `dpkg --info libefiboot1_37-6ubuntu3_riscv64.deb | grep 'Package'` we could identify the package name and look it up in /mnt/dists/mantic/main/binary-riscv64/Packages.gz to find out if a package of the same name is in the pool. If yes, remove the old package file.

**Comment by mwhudson** [comment]
While I can see this is a bit surprising, it's not really a bug, apt will always prefer the highest version of any given package name by default.

**Comment by xypron** [comment]
I guess we can close this if it does not stop apt from doing the right thing.
