### ISSUE TITLE
--cp command does not work

### ISSUE THREAD

**Issue by jw-rav** [mwhudson/livefs-editor#50]
Created ISO with this command:

cd /var/tmp/remaster.2L0ZrQo && \
  sudo PYTHONPATH=/m/src/remaster1/subiquity/livefs-editor \
       python3 -m livefs_edit --debug \
       /var/tmp/images/ubuntu-22.04.2-live-server-amd64.iso \
       /var/tmp/builds/ubuntu-remaster/my.iso \
       --inject-snap /m/src/remaster1/subiquity/subiquity-test.snap stable \
       --cp /m/src/remaster1/patches/instfiles/installer/etc/default/console-setup /etc/default/console-setup \
       --cp /m/src/remaster1/patches/instfiles/installer/etc/default/keyboard         /etc/default/keyboard

But the files meant to be copied still have the original contents (US keyboard/language instead of german)

**Comment by jw-rav** [comment]
Any ideas on this?

**Comment by mwhudson** [comment]
Oh wow I somehow missed this first time around.

```
--cp /m/src/remaster1/patches/instfiles/installer/etc/default/console-setup /etc/default/console-setup
```

That's two absolute paths, so it's copying your custom file to your actual /etc/default/console-setup, not touching the ISO at all! I'm not sure what you want to achieve with this tbh. Do you want to affect the behaviour of the installer or the installed system? (The latter would probably be easier done with late-commands in an autoinstall file)

**Comment by jw-rav** [comment]
Ah, I see..

I had the mis-conception that the second path would be a specification within the iso, as in subiquity/curtin. In addition, README.md talks about emulation of root FS and such things so I hat the impression that some kind of sandboxing is in effect under the hood.

Thanks!

Maybe you can also  elobarate on the  '$LAYER[n]' thing?
